apiVersion: stack.zncdata.net/v1alpha1
kind: ArgoWorkFlow
metadata:
  labels:
    app.kubernetes.io/name: argoworkflow
    app.kubernetes.io/instance: argoworkflow-sample
    app.kubernetes.io/part-of: argo-workflow-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: argo-workflow-operator
  name: argoworkflow-sample
spec:
  roleConfig:
    replicas: 3
    config:
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
  image:
    repository: bitnami/argo-workflow-controller
    tag: 3.5.0
    pullPolicy: IfNotPresent
  service:
    port: 18080
    type: ClusterIP
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  roleGroups:
    default:
      replicas: 1
